### ISSUE TITLE
develop current status indicator

### ISSUE THREAD

**Issue by hemeda55** [Evara-ZeLogic/Project-Monitoring-PM-#7]
for example " إنشاء وتجهيز مجمع المزارع النموذجية للإنتاج الحيواني بنجران" doesn't work
story no 1086

**Comment by Ssoliman2018** [comment]
done 
<img width="734" alt="Screenshot 2023-11-26 at 3 55 08 PM" src="https://github.com/Evara-ZeLogic/Project-Monitoring-PM-/assets/38067419/11d1185f-0296-41c7-9280-8cecdc6de0a7">

**Comment by Evara-Group** [comment]
![Image](https://github.com/Evara-ZeLogic/Project-Monitoring-PM-/assets/124177872/91725564-b173-4827-9203-71003deca2f1)

please Handel all this bugs

**Comment by Evara-Group** [comment]
![Image](https://github.com/Evara-ZeLogic/Project-Monitoring-PM-/assets/124177872/3d97c0a1-a448-46df-97bd-021fbc2350b4)

still not solved

**Comment by Ssoliman2018** [comment]
done 
<img width="1396" alt="Screenshot 2023-12-02 at 11 58 48 AM" src="https://github.com/Evara-ZeLogic/Project-Monitoring-PM-/assets/38067419/ff61c3cf-0ffa-42b0-9228-126078504e40">
